### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by darkjake** [LeoDJ/P2Pro-Viewer#10]
Heya! 

I wanna potentially work on fitting this and jerry rigging an app for vr headsets with the purpose of hunting, what is the current state of this before I purchase one? Not hoping for like picture captures and such, just hoping for basically red is hot functionality.

**Comment by LeoDJ** [comment]
Without any custom software, the P2 Pro is already "just a webcam" out of the box. It already does some image processing internally and provides a processed image (in addition to the raw data). 
By default the palette is white is hot.

If you want to change the palette to another built-in one, you can do so with the command `pseudo_color_set` in P2Pro_Cmd, assuming you have libusb-based access to the camera. Although the exact implementation depends on your system, ofc.
Otherwise you can always just map the black/white image to a color palette manually.

Additionally, I fear that the latency of this camera might pose a problem in a VR application.
I did not test the end-to-end latency and don't know which access method would provide the lowest latency, but it's easily in the 100s of ms, I'd guess. Which would be way too high for most VR applications, in my experience.

(I'll close this issue for now, as it's not an issue with this tool, but you can still comment)
