### ISSUE TITLE
Resolution/FPS of camera id 1 doesn't match. It's probably not a P2 Pro. 

### ISSUE THREAD

**Issue by Shonke** [LeoDJ/P2Pro-Viewer#3]
It seems to use my laptop camera.

This is the image I captured using obs:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/9344384/217816089-f106cd40-1dcc-491e-bfa6-b0239a440a32.png">

**Comment by LeoDJ** [comment]
This tool ist not done at all, that's why there's a big WIP (work in progress) disclaimer at the top of the README and a roadmap to see what's already implemented.

What you see on the main branch ist just the current state of development.
There is currently not even a GUI.

You just have to wait a bit. Once I'm done with the first milestone, I'll do an update post and create a "release".

But to answer your question directly, if you remove the "1" as the argument in line 16 in main.py, it should do a scan for the camera (takes some seconds, which is why I hardcoded it for testing) and just do a 5 second long recording to test.mkv, which is what I implemented and tested recently.
