### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by Arnold1** [LeoDJ/P2Pro-Viewer#5]
hi @LeoDJ,

great project! could you add some tutorial how to run it with a raspberry pi 2 w?

is there another open source api or driver to graph images or live video from the InfiRay P2 Pro?

is your project able to live grab a photo or video from the InfiRay P2 Pro?

whats the diff between the InfiRay P2 Pro a InfiRay Tiny1-B and a InfiRay Tiny1-C camera?
how much is the InfiRay Tiny1-B/Tiny1-C and where can you order it?
Can the InfiRay Tiny1-B/Tiny1-C can display the same images (RGB, etc.) as the InfiRay P2 Pro?

@TilCreator i see you use linux too - could you give some feedback?
@julled would also like to get your feedback on the SDK - could you give some feedback? is there an official SDK for the InfiRay P2 Pro?
Edit: InfriRay Tiny1-C SDK seems to be here: https://github.com/qw88888/rv1126

@LeoDJ did you look at https://github.com/yomboprime/yombir ? seems it works for both cameras?

Thanks

**Comment by Tomatendose** [comment]
Hi Arndold,

Have a look on the Internet for LineageOS. This will install Android on your Raspberry. There are some instructions to be found on the internet. Once this is done, the Google PlayStore must be installed. The original P2Pro software can then be installed from the store. This all worked without any problems. 

Greetings

**Comment by Arnold1** [comment]
Hi @Tomatendose,

i have not looked at LineageOS yet.
I would like to use my raspberry pi with linux and a InfiRay camera...

**Comment by TilCreator** [comment]
The #4 Fork should just work on any Linux machine as long as the dependencies are satisfied. But this project is still very WIP, have a look at the roadmap.

**Comment by Arnold1** [comment]
@TilCreator ok will look.

does anybody know the difference between a InfiRay P2 Pro and a InfiRay Tiny1-B/Tiny1-C?

**Comment by LeoDJ** [comment]
Sorry for the late reply, didn't have much time the last few months for this project.

Les has written a basic viewer for the Topdon TC001 (basically a InfiRay P2 Pro in another case) that works: https://github.com/leswright1977/PyThermalCamera 
But it doesn't support USB vendor commands, so no high-temperature mode.

If/once my tool is done, it will be able to capture pictures and videos with embedded raw thermal data too.
(Just the direct video recording part already works, but that's just the implementation, there is no GUI to interact with it yet.)

Tiny1 Modules:
From what I remember and had researched, the Tiny1-B module is pretty much what's inside a P2 Pro. 
And the Tiny1-C simply uses SPI+I²C (image+control) instead of USB (Tiny1-B) for communication.
They all use the InfiRay RTC2121 sensor. According to [mikeselectricstuff's teardown](https://youtu.be/YMQeXq1ujn0?t=1085) the P2 Pro also contains a Realtek RTS5813 IC (for the USB UVC stream). The Tiny1-B probably does too, but I'm not sure.

I don't know where to buy them from, probably only directly from InfiRay. There is a [forum post about the same question](https://www.eevblog.com/forum/thermal-imaging/contacting-infiray/).

SDK:
There is an SDK for the P2 Pro downloadable on the [old Xinfrared website](https://www.xinfrared.com/pages/download-center), but I don't want to take a look at the "official" source coude, because I try to keep my reverse-engineering as clean-room as possible.

Yombir looks interesting too, didn't know/try it yet.
